www/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// DEFINE CONSTANT
define( "SITE_ABRE" , "IBS");
define( "SITE_NAME" , "Iligan Buy and Sell");


// PAGES
Route::get('/', [
	'uses' => '\App\Http\Controllers\ItemController@index',
	'as' => 'home'
]);

Route::get('/about', function () {

    return view('about')
    		->with('pageTitle', SITE_ABRE . ' | About Us');

});

Route::get('/welcome', function () {

    return view('welcome');
    		//->with('pageTitle', SITE_ABRE . ' | About Us');

});


Route::group(['middleware' => ['auth'] ], function(){

	Route::resource('item', 'ItemController');

	Route::resource('type', 'TypeController');

	Route::resource('user', 'UserController', ['except' => ['create', 'store', 'show']]);
	Route::get('/myitem/{user_id}', 'ItemController@showMyItem');
	Route::post('/myitem/{user_id}', 'ItemController@showMyItem');

	Route::resource('comment.item.user', 'CommentController', [

		'parameters' => ['item'=>'item_id', 'user'=>'user_id']

		]);

	Route::resource('forums', 'ForumController');

});

Route::resource('category', 'CategoryController');

Route::resource('section', 'SectionController');

Route::resource('thumbnail', 'ThumbnailController');

//user resource must be define outside the group because the user.create route is called in the index.blade
Route::resource('user', 'UserController', ['only' => ['create', 'store', 'show']]);

Route::get('/search', 'ItemController@search');

Route::get('/sections/{section_id}', 'ItemController@showBySection');



//FACEBOOK
Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');
Route::post('/fblogin', 'SocialAuthController@store');

//Simple Authentication
Route::post('/login', [
	'uses' => '\App\Http\Controllers\Auth\AuthController@postLogin',
	'as' => 'auth.login'
]);

Route::get('/logout', [
	'uses' => '\App\Http\Controllers\Auth\AuthController@getLogout',
	'as' => 'logout'
]);

www/app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'user';
    protected $fillable = [
        'name', 'email', 'password', 'facebook_id', 'username', 'role_id', 'created_at', 'updated_at', 'remember_token', 'deleted_at', 'city_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function city(){
        return $this->belongsTo('App\City');
    }
}

www/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Item;
use App\User;
use App\Type;
use App\Category;
use Crypt;
use App\Http\Controllers\Controller;
use Auth;
use DateTime;
use Illuminate\Support\Facades\Redirect;
use Hash;
use App\ImageUpload;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::check()){
            $user = Auth::user();
            // $pass = Hash::make('123');
            $for_sell = Item::where('type_id', 2)->orderBy('updated_at', 'desc')->paginate(15);
            $looking_for = Item::where('type_id', 1)->orderBy('updated_at', 'desc')->paginate(15);

            $images = ImageUpload::get();

            return view('index', ['for_sell'=>$for_sell, 'looking_for'=>$looking_for, 'user'=>$user, 'images'=>$images])
                ->with('pageTitle', SITE_ABRE . ' | Home')
                ->with('user', $user);
        }

        return view('user.create')
            ->with('pageTitle', SITE_ABRE . ' | Register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // Sometimes you may wish to stop running validation rules on an attribute after the first validation failure. To do so, assign the bail rule to the attribute: 'title' => 'bail|required|unique:posts|max:255'
        $this->validate($request, [
            'username' => 'required|unique:user|max:255',
            'email' => 'required|unique:user|max:255',
            'password' => 'required',
        ]);

        $now = new DateTime();
        $timestamp = $now->getTimestamp();
        $user = new User;

        $user->username = $request->input('username');
        $user->password = Hash::make($request->input('password') );
        $user->facebook_id = $request->input('facebook_id');
        $user->name = $request->input('name');
        $user->email = $request->input('fb_email');
        $user->remember_token = $request->input('token');
        $user->role_id = 2;
        $user->city_id = 792;
        $user->created_at = $timestamp;
        $user->save();
        return Redirect::back()->withSuccess('Successfully registered ' . $user->name);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::where('id', $id)->get()->first();
        $items = Item::where('user_id', $id)->get();

        if($user){
            return view('user.show')
                ->with('user', $user)
                ->with('items', $items)
                ->with('pageTitle', SITE_ABRE . ' | ' . $user->name);
        }

        return 'ERROR 404';
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::where('id', Auth::user()->id)
                    ->get()
                    ->first();

        return view('user.edit')
                ->with('pageTitle', SITE_ABRE . ' | Edit Profile')
                ->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        // Sometimes you may wish to stop running validation rules on an attribute after the first validation failure. To do so, assign the bail rule to the attribute: 'title' => 'bail|required|unique:posts|max:255'
        $this->validate($request, [
            //unique:user,id,:id means that exclude this user from checking if the username or email exist
            'username' => 'required|unique:user,id,:id|max:255',
            'email' => 'required|unique:user,id,:id|max:255',
            'name' => 'required|max:50',
            'password_confirm' => 'same:password',
        ]);

        $user = User::where('id', Auth::user()->id )
                    ->get()
                    ->first();

        $now = new DateTime();
        $timestamp = $now->getTimestamp();


        $user->name = $request->input('name');
        $user->username = $request->input('username');
        $user->email = $request->input('email');
        $user->contact = $request->input('contact');
        $user->updated_at = $timestamp;
        $user->address = $request->input('address');
        //has password
        $pass = Hash::make($request->input('password'));

        if(!empty( $request->input('password') )){
            $user->password = $pass;
        }

        $user->role_id = 2;
        $user->city_id = 792;

        $user->save();

        return redirect()->action('UserController@show', $user->id)
                        ->with('update', 'Successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

www/resources/views/user/create.blade.php
@extends('layout.default')

@section('content')

	<div class="container-fluid">

		<div class="row">

			<div class="col-md-10">

				<div class="row">

					<div class="col-md-12">

						<div class="alert alert-dismissible alert-info">
						  <!-- <button type="button" class="close" data-dismiss="alert"><i class="fa fa-times"></i></button> -->
						  <h4>Welcome to IBS | Iligan Buy and Sell!</h4>
						  <p>The best place to Buy a house, Sell a car or Find a job in Iligan City.</p>
						</div>


					</div>

				</div>

				<div class="row">

					{{-- Selling Section / Categories Section --}}
		  			<div class="col-md-6">

		  				<div class="panel panel-default">
		  				@if(Auth::guest())
							<div class="panel-heading">
							    <h3 class="panel-title">Iligan Buy and Sell Registration</h3>
							</div>
							<div class="panel-body">
							    	@if( Session::has( 'success' ))
							    	<div class="alert alert-success">
									     {{ Session::get( 'success' ) }}
									</div>

									@elseif($errors)
								     	@foreach($errors->all() as $error)
								     		<div class="alert alert-danger">
								     			{{ $error }}
								     		</div>
								     	@endforeach
									@endif


							    <form method="POST" action="{{route('user.store')}}">

							    	{!! csrf_field() !!}

							    	<div class="form-group">
									    <label>Name</label>
									   	<input type="text" class="form-control" name="name" placeholder="">
									</div>

									<div class="form-group">
										<label>Email</label>
    									<input type="text" class="form-control" name="email" placeholder="">
    								</div>

    								<div class="form-group">
										<label>Username</label>
    									<input type="text" class="form-control" name="username" placeholder="">
    								</div>

    								<div class="form-group">
									    <label>Password</label>
									   	<input type="password" class="form-control" name="password" placeholder="">
									</div>

    								<div class="form-group">
    									<button type="submit" class="btn btn-primary">Create my Account!</button>
    								</div>

							    </form>

							</div>

						@elseif(Auth::check())
					    <div class="alert alert-warning">
						  <strong>Warning!</strong> You're currently logged in.
						</div>
						@endif
						</div>



		  			</div>
		  			{{-- //Selling Section / Categories Section--}}

		  			{{-- Buying Section --}}
		  			<div class="col-md-6">

		  				<div class="panel panel-warning">
							<div class="panel-heading">
							    <h3 class="panel-title">Basic Posting Item Guideline</h3>
							</div>
							<div class="panel-body">
							    <p>You can list as many items as you want in the buy/sell section. Here are the requirements and recommendations for adding product images, descriptions and variants.</p>
							    <ul>

							    	<li>At least one image is required for each product. Are easy to understand and show the whole product</li>
							    	<li>Description, should be rich text only (no HTML). Provide only information directly related to the product. Make use of short sentences.</li>
							    	<li>You will not post items in the a section that do not fall under any of the defined categories.</li>
							    	<li>By posting items in the IBS, you guarantee that your item has been legally purchased or acquired. IBS will not be liable for any false, misleading or inaccurate representations by its users.</li>

							    </ul>
							</div>
						</div>



		  			</div>
		  			{{-- //Buying Section --}}

				</div>

			</div>

			<div class="col-md-2">

					@include('layout.left-side')

			</div>

		</div>

	</div>

@endsection

www/resources/views/user/edit.blade.php
@extends('layout.lte-default')

@section('content')

	<div class="container-fluid">


		<div id="search-from-item-create" style="display:none" class="row">

			<div class="col-md-12">

				<div class="row">

					{{-- Selling Section / Categories Section --}}
		  			<div class="col-md-6">

		  				<div class="panel panel-success">
							<div class="panel-heading">
							    <h3 class="panel-title">Selling Section</h3>
							</div>
							<div id="selling-section" class="panel-body ibs-panel-body">

							</div>
						</div>



		  			</div>
		  			{{-- //Selling Section / Categories Section--}}

		  			{{-- Buying Section --}}
		  			<div class="col-md-6">

		  				<div class="panel panel-info">
							<div class="panel-heading">
							    <h3 class="panel-title">Buying Section</h3>
							</div>
							<div id="buying-section" class="panel-body ibs-panel-body">

							</div>
						</div>



		  			</div>
		  			{{-- //Buying Section --}}

				</div>

			</div>


		</div>

		<div id="user-edit" class="row">

			<div class="col-md-10">

				<div class="row">

					{{-- Selling Section / Categories Section --}}
		  			<div class="col-md-6">

		  				<div class="panel panel-default">
		  				@if(Auth::check())
							<div class="panel-heading">
							    <h3 class="panel-title">Iligan Buy and Sell Registration</h3>
							</div>
							<div class="panel-body">
							    	@if( Session::has( 'success' ))
							    	<div class="alert alert-success">
									     {{ Session::get( 'success' ) }}
									</div>
									@elseif( $errors )
										@foreach($errors->all() as $error)
											<div class="alert alert-danger">
											     {{ $error }} <!-- here to 'withWarning()' -->
											</div>
										@endforeach
									@endif


							    <form method="POST" action="{{route('user.update', Auth::user()->id)}}">

							    	{!! csrf_field() !!}
							    	{!! method_field('put') !!}

							    	<div class="form-group">
									    <label>Name</label>
									   	<input type="text" class="form-control" name="name" value="{{$user->name}}" required="">
									</div>

									<div class="form-group">
										<label>Email</label>
    									<input type="text" class="form-control" name="email" value="{{$user->email}}" required="">
    								</div>

    								<div class="form-group">
										<label>Username</label>
    									<input type="text" class="form-control" name="username" value="{{$user->username}}" required>
    								</div>

    								<div class="form-group">
										<label>Contact</label>
    									<input type="text" class="form-control" name="contact" value="{{$user->contact}}">
    								</div>

    								<div class="form-group">
										<label>Address</label>
    									<input type="text" class="form-control" name="address" value="{{$user->address}}">
    								</div>

    								<div class="form-group">
									    <label>Password</label>
									   	<input type="password" class="form-control" name="password">
									</div>

									<div class="form-group">
									    <label>Confirm Password</label>
									   	<input type="password" class="form-control" name="password_confirm">
									</div>

    								<div class="form-group">
    									<button type="submit" class="btn btn-primary">Update my Account!</button>
    								</div>

							    </form>

							</div>

						@elseif(Auth::guest())
					    <div class="alert alert-warning">
						  <strong>Warning!</strong> Please logged in.
						</div>
						@endif
						</div>



		  			</div>
		  			{{-- //Selling Section / Categories Section--}}

				</div>

			</div>

			<div class="col-md-2">

					@include('layout.left-side')

			</div>

		</div>

	</div>

@endsection

www/resources/views/user/show.blade.php
@extends('layout.lte-default')

@section('content')

	<div class="container-fluid">


		<div id="search-from-item-create" style="display:none" class="row">

			<div class="col-md-12">

				<div class="row">

					{{-- Selling Section / Categories Section --}}
		  			<div class="col-md-6">

		  				<div class="panel panel-success">
							<div class="panel-heading">
							    <h3 class="panel-title">Selling Section</h3>
							</div>
							<div id="selling-section" class="panel-body ibs-panel-body">

							</div>
						</div>



		  			</div>
		  			{{-- //Selling Section / Categories Section--}}

		  			{{-- Buying Section --}}
		  			<div class="col-md-6">

		  				<div class="panel panel-info">
							<div class="panel-heading">
							    <h3 class="panel-title">Buying Section</h3>
							</div>
							<div id="buying-section" class="panel-body ibs-panel-body">

							</div>
						</div>



		  			</div>
		  			{{-- //Buying Section --}}

				</div>

			</div>


		</div>

		<div id="user-show" class="row">

			<div class="col-md-10">

				<div class="row">

					@if( session( 'update' ))
					    <div class="alert alert-success">
							{{ session( 'update' ) }}
						</div>
					@endif

					{{-- Selling Section / Categories Section --}}
		  			<div class="col-md-12">

		  				<div class="panel panel-default">
							<div class="panel-heading">
							    <h1>{{ $user->name }}</h1>
							    <h4>{{ $user->email }}</h4>

							</div>

							<div class="panel-body">

								<p>Account type:
								@if($user->role_id==2)
									Regular
								@else
									Premium
								@endif
								</p>

								<p>Contact: {{ $user->contact }}</p>
								<p>Address: {{ $user->address }}</p>

							</div>

						</div>



		  			</div>
		  			{{-- //Selling Section / Categories Section--}}


				</div>


				<div class="row">
					<div class="col-md-12">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h3>{{ $user->name }} posted this item(s)</h3>
							</div>

							<div class="panel-body">
								{{-- Selling Section / Categories Section --}}
					  			<div class="col-md-6">

					  				<div class="panel panel-success">
										<div class="panel-heading">
										    <h3 class="panel-title">For Sell</h3>
										</div>
										<div class="panel-body">
											@foreach($items as $item)
												@if ($item->type_id == 2)
													<h2><a href="{{ route('item.show', $item->id) }}">{{$item->name}}</a></h2>
													<p>{{ $item->description }}</p>
												@endif
											@endforeach
										</div>
									</div>
					  			</div>
					  			{{-- //Selling Section / Categories Section--}}

					  			{{-- Buying Section --}}
					  			<div class="col-md-6">

					  				<div class="panel panel-info">
										<div class="panel-heading">
										    <h3 class="panel-title">Looking For This Item(s)</h3>
										</div>
										<div class="panel-body">
										    @foreach($items as $item)
												@if ($item->type_id == 1)
													<h2>
														<a href="{{ route('item.show', $item->id) }}">{{$item->name}}</a>
													</h2>
													<p>{{ $item->description }}</p>
												@endif
											@endforeach
										</div>
									</div>
					  			</div>
					  			{{-- //Buying Section --}}
				  			</div>
				  		</div>
			  		</div>
				</div>


			</div>

			<div class="col-md-2">

					@include('layout.left-side')

			</div>

		</div>

	</div>

@endsection