www/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// DEFINE CONSTANT
define( "SITE_ABRE" , "IBS");
define( "SITE_NAME" , "Iligan Buy and Sell");


// PAGES
Route::get('/', [
	'uses' => '\App\Http\Controllers\ItemController@index',
	'as' => 'home'
]);

Route::get('/about', function () {

    return view('about')
    		->with('pageTitle', SITE_ABRE . ' | About Us');

});

Route::get('/welcome', function () {

    return view('welcome');
    		//->with('pageTitle', SITE_ABRE . ' | About Us');

});


Route::group(['middleware' => ['auth'] ], function(){

	Route::resource('item', 'ItemController');

	Route::resource('type', 'TypeController');

	Route::resource('user', 'UserController', ['except' => ['create', 'store', 'show']]);
	Route::get('/myitem/{user_id}', 'ItemController@showMyItem');
	Route::post('/myitem/{user_id}', 'ItemController@showMyItem');

	Route::resource('comment.item.user', 'CommentController', [

		'parameters' => ['item'=>'item_id', 'user'=>'user_id']

		]);

	Route::resource('forums', 'ForumController');

});

Route::resource('category', 'CategoryController');

Route::resource('section', 'SectionController');

Route::resource('thumbnail', 'ThumbnailController');

//user resource must be define outside the group because the user.create route is called in the index.blade
Route::resource('user', 'UserController', ['only' => ['create', 'store', 'show']]);

Route::get('/search', 'ItemController@search');

Route::get('/sections/{section_id}', 'ItemController@showBySection');



//FACEBOOK
Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');
Route::post('/fblogin', 'SocialAuthController@store');

//Simple Authentication
Route::post('/login', [
	'uses' => '\App\Http\Controllers\Auth\AuthController@postLogin',
	'as' => 'auth.login'
]);

Route::get('/logout', [
	'uses' => '\App\Http\Controllers\Auth\AuthController@getLogout',
	'as' => 'logout'
]);

www/app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $table = 'item';
    protected $fillable = array('name', 'price', 'description', 'created_at', 'updated_at', 'type_id',
    							'category_id', 'user_id', 'is_active');

    public function user(){
    	return $this->belongsTo('App\User');
    }
    public function category(){
    	return $this->belongsTo('App\Category');
    }
    public function type(){
    	return $this->belongsTo('App\Type');
    }
}

www/app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Item;
use App\User;
use App\Thumbnail;
use App\Type;
use App\Category;
use App\Section;
use App\ImageUpload;
use App\Comment;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Auth;
use DateTime;
use Illuminate\Support\Facades\Redirect;
use Hash;
use Illuminate\Support\Facades\Input;
use Illuminate\Pagination\LengthAwarePaginator;


// import the Intervention Image Manager Class
use Intervention\Image\ImageManagerStatic as Image;

// configure with favored image driver (gd by default)
Image::configure(array('driver' => 'gd'));

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $for_sell = Item::where('type_id', 2)
                        ->where('is_active', true)
                        ->orderBy('updated_at', 'desc')
                        ->paginate(15);

        $looking_for = Item::where('type_id', 1)
                            ->where('is_active', true)
                            ->orderBy('updated_at', 'desc')
                            ->paginate(15);

        $thumbnails = Thumbnail::get();
        $user = Auth::user();
        // $pass = Hash::make('123');

        if ( $user ) {

            return view('index', ['for_sell'=>$for_sell, 'looking_for'=>$looking_for, 'user'=>$user, 'thumbnails'=>$thumbnails])
                ->with('pageTitle', SITE_NAME . ' | The best place to Buy a house, Sell a car or Find a job in Iligan City.')
                ->with('user', $user);
                // ->with('pass', $pass);
            //return $pass;
        }

        else {

            return view('welcome', ['for_sell'=>$for_sell, 'looking_for'=>$looking_for, 'user'=>$user, 'thumbnails'=>$thumbnails])
                ->with('pageTitle', SITE_NAME . ' | The best place to Buy a house, Sell a car or Find a job in Iligan City.')
                ->with('user', $user);
                // ->with('pass', $pass);
            //return $pass;
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = Type::all();
        $sections = Section::all();
        $user = Auth::user();

        return view('item.create', ['types'=>$types, 'sections'=>$sections, 'user'=>$user])
            ->with('pageTitle', SITE_ABRE . ' | Create Item');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $item = new Item;
        $now = new DateTime();
        $user = Auth::user();
        $timestamp = $now->getTimestamp();

        $this->validate($request, [
            'name' => 'required|max:255',
            'type_id' => 'required',
            'category_id' => 'required',
        ]);

        $item->name = $request->input('name');
        $item->price = $request->input('price');
        $item->description = $request->input('description');
        $item->created_at = $timestamp;
        $item->updated_at = $timestamp;
        $item->type_id = $request->input('type_id');
        $item->category_id = $request->input('category_id');
        $item->user_id = $user->id;
        $item->save();

        //creating the image
        $images = Input::file('images');

        if(!$images){
            $items = Item::orderBy('updated_at', 'desc')->where('is_active', true)->get();

            return Redirect::back()->withSuccess('Successfully added item ' . $item->name)
                    ->with('user', $user);
        }

        $filename  = time() . '.' . $images->getClientOriginalExtension();
        $thumbnail_name = 'thumbnail' . time() . '.' . $images->getClientOriginalExtension();
        $path = public_path('img/' . $filename);
        $thumbnail_path = public_path('img/' . $thumbnail_name);
        Image::make($images->getRealPath())->pixelate(1)->resize(304,236)->save($path);
        Image::make($images->getRealPath())->pixelate(1)->resize(64,64)->save($thumbnail_path);

        $image = new ImageUpload;
        $thumbnail = new Thumbnail;

        $image->name = $filename;
        $image->directory = $filename;
        $image->created_at = $timestamp;
        $image->updated_at = $timestamp;
        $image->item_id = $item->id;

        $thumbnail->name = $thumbnail_name;
        $thumbnail->item_id = $item->id;
        $thumbnail->created_at = $timestamp;
        $thumbnail->updated_at = $timestamp;

        // $image_make->fit(300, 200);

        // $image_make->save('../resources/views/item/images/'. $image_name);

        $image->save();
        $thumbnail->save();


        $items = Item::orderBy('updated_at', 'desc')->where('is_active', true)->get();

        return Redirect::back()->withSuccess('Successfully added item ' . $item->name)
                ->with('user', $user);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = Item::where('id', '=' , $id)->where('is_active', true)->get()->first();
        $images = ImageUpload::where('item_id', $item->id)->get()->first();
        $user = Auth::user();
        $comments = Comment::orderBy('created_at', 'desc')->where('item_id', $id)->get();

        return view('item.show', ['item'=>$item, 'user'=>$user, 'comments'=>$comments, 'images'=>$images])
            ->with('pageTitle', SITE_ABRE . ' | View Item');
    }

    public function showMyItem($user_id)
    {
        $items = Item::where('user_id', '=' , $user_id)->where('is_active', true)->get();
        $user = Auth::user();
        $thumbnails = Thumbnail::get();

        return view('item.myItem', ['items'=>$items, 'user'=>$user, 'thumbnails'=>$thumbnails])
            ->with('pageTitle', SITE_ABRE . ' | My Items');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // if(Auth::check()){
        //     $item = Item::where('id', $id)->where('is_active', true)->get()->first();
        //     $images = ImageUpload::where('item_id', $id)->where('is_active', true)->get()->first();
        //     $user = Auth::user();

        //     return view('item.edit')
        //             ->with('item', $item)
        //             ->with('images', $images)
        //             ->with('user', $user);
        // }

        $item = Item::where('id', $id)->where('is_active', true)->get()->first();
        $images = ImageUpload::where('item_id', $id)->get()->first();
        $types = Type::get();
        $sections = Section::get();

        return view('item.edit')
                    ->with('item', $item)
                    ->with('types', $types)
                    ->with('images', $images)
                    ->with('sections', $sections)
                    ->with('pageTitle', SITE_ABRE . ' | Update Item');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $now = new DateTime();
        $timestamp = $now->getTimestamp();

        $this->validate($request, [
            'name' => 'required|max:255',
            'type_id' => 'required',
            'category_id' => 'required',
        ]);

        $item = Item::where('id', $id)->get()->first();
        $item->type_id = $request->input('type_id');
        $item->name = $request->input('name');
        $item->description = $request->input('description');
        $item->category_id = $request->input('category_id');
        $item->price = $request->input('price');
        $item->updated_at = $timestamp;
        $item->save();


        $items = Item::where('user_id', Auth::user()->id)->get();
        $user = User::where('id', Auth::user()->id)->get();
        $thumbnails = Thumbnail::get();

        if (Input::file('images')) {
            $img = ImageUpload::where('item_id', $item->id)->get()->first();
            if ($img) {
                Storage::delete($image->name);
                $images = Input::file('images');

                $filename  = time() . '.' . $images->getClientOriginalExtension();
                $thumbnail_name = 'thumbnail' . time() . '.' . $images->getClientOriginalExtension();
                $path = public_path('img/' . $filename);
                $thumbnail_path = public_path('img/' . $thumbnail_name);
                Image::make($images->getRealPath())->pixelate(1)->resize(304,236)->save($path);
                Image::make($images->getRealPath())->pixelate(1)->resize(64,64)->save($thumbnail_path);

                $image = new ImageUpload;
                $thumbnail = new Thumbnail;

                $image->name = $filename;
                $image->directory = $filename;
                $image->created_at = $timestamp;
                $image->updated_at = $timestamp;
                $image->item_id = $item->id;

                $thumbnail->name = $thumbnail_name;
                $thumbnail->item_id = $item->id;
                $thumbnail->created_at = $timestamp;
                $thumbnail->updated_at = $timestamp;

                // $image_make->fit(300, 200);

                // $image_make->save('../resources/views/item/images/'. $image_name);

                $image->save();
                $thumbnail->save();

                return 'exist image';

            }

            $now = new DateTime();
            $timestamp = $now->getTimestamp();

            $images = Input::file('images');

www/resources/views/item/create.blade.php
@extends('layout.lte-default')

@section('content')

	<div class="container-fluid">

		<div id="search-from-item-create" style="display:none" class="row">

			<div class="col-md-12">

				<div class="row">

					{{-- Selling Section / Categories Section --}}
		  			<div class="col-md-6">

		  				<div class="panel panel-success">
							<div class="panel-heading">
							    <h3 class="panel-title">Selling Section</h3>
							</div>
							<div id="selling-section" class="panel-body ibs-panel-body">

							</div>
						</div>



		  			</div>
		  			{{-- //Selling Section / Categories Section--}}

		  			{{-- Buying Section --}}
		  			<div class="col-md-6">

		  				<div class="panel panel-info">
							<div class="panel-heading">
							    <h3 class="panel-title">Buying Section</h3>
							</div>
							<div id="buying-section" class="panel-body ibs-panel-body">

							</div>
						</div>



		  			</div>
		  			{{-- //Buying Section --}}

				</div>

			</div>


		</div>

		<div id="item-create" class="row">

			<div class="col-md-10">

				<div class="row">

		  			<div class="col-md-6">

		  				<div class="panel panel-warning">
							<div class="panel-heading">
							    <h3 class="panel-title">Basic Posting Item Guideline</h3>
							</div>
							<div class="panel-body">
							    <p>You can list as many items as you want in the buy/sell section. Here are the requirements and recommendations for adding product images, descriptions and variants.</p>
							    <ul>

							    	<li>At least one image is required for each product. Are easy to understand and show the whole product</li>
							    	<li>Description, should be rich text only (no HTML). Provide only information directly related to the product. Make use of short sentences.</li>
							    	<li>You will not post items in the a section that do not fall under any of the defined categories.</li>
							    	<li>By posting items in the IBS, you guarantee that your item has been legally purchased or acquired. IBS will not be liable for any false, misleading or inaccurate representations by its users.</li>

							    </ul>
							</div>
						</div>



		  			</div>

		  			<div class="col-md-6">

		  				<div class="panel panel-default">
		  				@if(Auth::check())
							<div class="panel-heading">
							    <h3 class="panel-title">Item Information</h3>
							</div>
							<div class="panel-body">
							    	@if( Session::has( 'success' ))
							    	<div class="alert alert-success">
									     {{ Session::get( 'success' ) }}
									</div>
									@elseif( Session::has( 'warning' ))
									<div class="alert alert-danger">
									     {{ Session::get( 'warning' ) }} <!-- here to 'withWarning()' -->
									</div>

									@elseif($errors)
								     	@foreach($errors->all() as $error)
								     		<div class="alert alert-danger">
								     			{{ $error }} | Please choose section first.
								     		</div>
								     	@endforeach
									@endif


							    <form id="create_item_form" method="POST" action="{{route('item.store')}}" enctype="multipart/form-data">

							    	{!! csrf_field() !!}

							    	<div class="form-group">
									    <label for="inputSection">Type</label>
									   	<select name="type_id" class="form-control input-sm">
									   		@foreach($types as $type)
									   			<option value="{{$type->id}}">{{ $type->name }}</option>
									   		@endforeach
										</select>
									</div>

									<div class="form-group">
										<label for="inputItemName">Item Name</label>
    									<input type="text" class="form-control" name="name" id="inputItemName" placeholder="">
    								</div>

    								<div class="form-group">
										<label for="inputItemDescription">Item Description</label>
    									<textarea name="description" rows="4" cols="50"></textarea>
    								</div>

    								<div class="form-group">
									    <label for="inputCategory">Section</label>
									   	<select onChange="show_categories();" id="section_id" name="section_id" class="form-control input-sm">
									   		<option value="0">Please select property section</option>
									   		@foreach($sections as $section)
									   			<option value="{{ $section->id }}">{{ $section->name }}</option>
									   		@endforeach
										</select>
									</div>

                                    <div id="sectionloading" class="form-group" style="display:none">
                                        <center><img src="/img/sectionloading.gif" alt="" /></center>

                                    </div>

									<div id="category_view" style="display:none" class="form-group">
									    <label>Category</label>
									   	<select id="category_id" name="category_id" class="form-control input-sm">

										</select>
									</div>

									<div class="form-group">
										<label for="inputPrice">Price or Budget (Php)</label>
    									<input name="price" type="number" class="form-control" id="inputPrice" placeholder="">
    								</div>

    								<div class="form-group">
										<label >Image max: 1</label>
    									<input id="sample_input" name="images" type="file" class="form-control">
    								</div>

    								<div class="form-group">
    									<button type="submit" class="btn btn-primary">Post</button>
    								</div>

							    </form>

							</div>

						@elseif(!Auth::check())

							<div class="panel-heading">
							    <h3 class="panel-title">Please Login First.</h3>
							</div>

							<div class="panel-body">
							    <form role="form" method="post" action="{{ route('auth.login') }}">

									<input type="hidden" name="_token" value="{{ Session::token() }}">

									<div class="form-group">
									    <label for="username">Username:</label>
									    <input type="text" class="form-control input-sm" id="username" placeholder="Username" name="username">
									</div>

									<div class="form-group">
									    <label for="password">Password:</label>
									    <input type="password" class="form-control input-sm" id="password" placeholder="Password" name="password">
									</div>

									<button type="submit" class="btn btn-primary btn-xs">Login</button>
									<a class="btn btn-success btn-xs" href="{{ route('user.create') }}">Register</a>

									@if (session('info'))
		                                <span class="bg-warning">{{ session('info') }}</span>
		                            @endif

								</form>
							</div>

						@endif
						</div>



		  			</div>



				</div>

			</div>

			<div class="col-md-2">

					@include('layout.left-side')

			</div>

		</div>

	</div>

@endsection

www/resources/views/item/edit.blade.php
@extends('layout.lte-default')

@section('content')

	<div class="container-fluid">

		<div id="search-from-item-create" style="display:none" class="row">

			<div class="col-md-12">

				<div class="row">

					{{-- Selling Section / Categories Section --}}
					<div class="col-md-6">

						<div class="panel panel-success">
							<div class="panel-heading">
								<h3 class="panel-title">Selling Section</h3>
							</div>
							<div id="selling-section" class="panel-body ibs-panel-body">

							</div>
						</div>



					</div>
					{{-- //Selling Section / Categories Section--}}

					{{-- Buying Section --}}
					<div class="col-md-6">

						<div class="panel panel-info">
							<div class="panel-heading">
								<h3 class="panel-title">Buying Section</h3>
							</div>
							<div id="buying-section" class="panel-body ibs-panel-body">

							</div>
						</div>



					</div>
					{{-- //Buying Section --}}

				</div>

			</div>


		</div>

		<div id="item-edit" class="row">

			<div class="col-md-10">

				<div class="row">

					{{-- Selling Section / Categories Section --}}
		  			<div class="col-md-12">

		  				<div class="panel panel-default">
							<div class="panel-heading">
							    <h3 class="panel-title">Item Information</h3>
							</div>
							<div class="panel-body">

							    <div class="col-md-6">


									@if($errors)
										@foreach($errors->all() as $error)
											<div class="alert alert-danger">
												{{ $error }} | Please choose section first.
											</div>
										@endforeach
									@endif

									<form method="POST" action="{{route('item.update', $item->id)}}" enctype="multipart/form-data">

								    	{!! csrf_field() !!}
										{!! method_field('put') !!}

								    	<div class="form-group">
										    <label for="inputSection">Type</label>
										   	<select name="type_id" class="form-control input-sm">
										   		@foreach($types as $type)
										   			<option value="{{$type->id}}">{{ $type->name }}</option>
										   		@endforeach
											</select>
										</div>

										<div class="form-group">
											<label for="inputItemName">Item Name</label>
	    									<input type="text" class="form-control" name="name" id="inputItemName" value="{{ $item->name }}">
	    								</div>

	    								<div class="form-group">
											<label for="inputItemDescription">Item Description</label>
	    									<textarea name="description" rows="4" cols="50">{{ $item->description }}</textarea>
	    								</div>

										<div class="form-group">
										    <label for="inputCategory">Section</label>
										   	<select onChange="show_categories();" id="section_id" name="section_id" class="form-control input-sm">
										   		<option value="0">Please select property section</option>
										   		@foreach($sections as $section)
										   			<option value="{{ $section->id }}">{{ $section->name }}</option>
										   		@endforeach
											</select>
										</div>

										<div id="sectionloading" class="form-group" style="display:none">
	                                        <center><img src="/img/sectionloading.gif" alt="" /></center>

	                                    </div>

										<div id="category_view" style="display:none" class="form-group">
										    <label>Category</label>
										   	<select id="category_id" name="category_id" class="form-control input-sm">

											</select>
										</div>

										<div class="form-group">
											<label for="inputPrice">Price or Budget (Php)</label>
	    									<input name="price" type="number" class="form-control" id="inputPrice" value="{{ $item->price }}">
	    								</div>

										@if($images==null)
											<div class="form-group">
												<label >Update Image</label>
												<input id="sample_input" name="images" type="file" class="form-control">
											</div>
										@endif
										<div class="form-group">
	    									<button type="submit" class="btn btn-primary">Update</button>
	    								</div>
							    	</form>
								</div>

								<div class="col-md-6">
								@if($images!=null)
									<img width="304" height="236" src="{{ asset('/www/public/img/'.$images->name) }}"><br>
									<a href="{{ route('item.destroy', $item->id) }}"><button class="btn btn-warning">Delete this item</button></a>
								@endif
								</div>

							</div>
						</div>


		  			</div>
		  			{{-- //Selling Section / Categories Section--}}


				</div>

			</div>

			<div class="col-md-2">

					@if(!Auth::check())

					@include('layout.left-side')

					@else
					@include('layout.left-side')

					@endif


			</div>

		</div>

	</div>

@endsection

www/resources/views/item/show.blade.php
@extends('layout.lte-default')

@section('content')

	<div class="container-fluid">

		<div class="row">

			<div class="col-md-10">

				<div class="row">

					{{-- Selling Section / Categories Section --}}
		  			<div class="col-md-12">

		  				<div class="panel panel-default">
							<div class="panel-heading">
							    <h3 class="panel-title">Item Information</h3>
							</div>
							<div class="panel-body">

							    <div class="col-md-6">
									<h1>{{$item->name}}</h1>
									<p>Price: ₱ {{ $item->price }}</p>
									<p>Posted by: <a href="{{ route('user.show', $item->user->id) }}">{{$item->user->name}}</a> | {{ $item->created_at }}</p><br>
									<p>
										<h3>Description</h3>
										{{ $item->description }}
									</p>
								</div>

								<div class="col-md-6">
								@if($images!=null)
									<img width="304" height="236" src="{{ asset('/www/public/img/'.$images->name) }}">
								@endif
								</div>

							</div>
						</div>

						<div class="panel panel-default">
							<div class="panel-heading">
							    <h3 class="panel-title">Comment(s)</h3>
							</div>
							<div class="panel-body">
							    @if(Auth::check())
									<form method="POST" action="{{ route('comment.item.user.store', [$item->id, Auth::user()->id]) }}">

								    	{!! csrf_field() !!}

										<div class="form-group">
	    									<input name="comment" type="text" class="form-control" placeholder="write comment...">
	    									<button type="submit" class="btn btn-primary">Post</button>
	    								</div>

								    </form>
								@else <p>Please Log in to post comment(s)</p>
							    @endif

							    @foreach($comments as $comment)
							    	<p>{{$comment->user->name}} says: {{$comment->comment}}</p>
							    @endforeach

							</div>
						</div>



		  			</div>
		  			{{-- //Selling Section / Categories Section--}}


				</div>

			</div>

			<div class="col-md-2">

					@if(!Auth::check())

					@include('layout.left-side')

					@else
					@include('layout.left-side')

					@endif


			</div>

		</div>

	</div>

@endsection