www/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// DEFINE CONSTANT
define( "SITE_ABRE" , "IBS");
define( "SITE_NAME" , "Iligan Buy and Sell");


// PAGES
Route::get('/', [
	'uses' => '\App\Http\Controllers\ItemController@index',
	'as' => 'home'
]);

Route::get('/about', function () {

    return view('about')
    		->with('pageTitle', SITE_ABRE . ' | About Us');

});

Route::get('/welcome', function () {

    return view('welcome');
    		//->with('pageTitle', SITE_ABRE . ' | About Us');

});


Route::group(['middleware' => ['auth'] ], function(){

	Route::resource('item', 'ItemController');

	Route::resource('type', 'TypeController');

	Route::resource('user', 'UserController', ['except' => ['create', 'store', 'show']]);
	Route::get('/myitem/{user_id}', 'ItemController@showMyItem');
	Route::post('/myitem/{user_id}', 'ItemController@showMyItem');

	Route::resource('comment.item.user', 'CommentController', [

		'parameters' => ['item'=>'item_id', 'user'=>'user_id']

		]);

	Route::resource('forums', 'ForumController');

});

Route::resource('category', 'CategoryController');

Route::resource('section', 'SectionController');

Route::resource('thumbnail', 'ThumbnailController');

//user resource must be define outside the group because the user.create route is called in the index.blade
Route::resource('user', 'UserController', ['only' => ['create', 'store', 'show']]);

Route::get('/search', 'ItemController@search');

Route::get('/sections/{section_id}', 'ItemController@showBySection');



//FACEBOOK
Route::get('/redirect', 'SocialAuthController@redirect');
Route::get('/callback', 'SocialAuthController@callback');
Route::post('/fblogin', 'SocialAuthController@store');

//Simple Authentication
Route::post('/login', [
	'uses' => '\App\Http\Controllers\Auth\AuthController@postLogin',
	'as' => 'auth.login'
]);

Route::get('/logout', [
	'uses' => '\App\Http\Controllers\Auth\AuthController@getLogout',
	'as' => 'logout'
]);

www/resources/views/layout/partials/footer.blade.php
	<!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
            IBS Web Team
        </div>
            <!-- Default to the left -->
        <strong>Copyright © 2016 <a href="{{ url('/') }}">Iligan Buy and Sell</a>.</strong> All rights reserved.
    </footer>

www/resources/views/layout/partials/header.blade.php
    <!-- Main Header -->
	<header class="main-header">

		<!-- Logo -->
    	<a href="{{ url('/') }}" class="logo">
	      	<!-- mini logo for sidebar mini 50x50 pixels -->
	      	<span class="logo-mini"><img alt="Brand" width="20" height="20" src="{{ asset('/img/logo.png') }}"></span>
	      	<!-- logo for regular state and mobile devices -->
	      	<span class="logo-lg"><img alt="Brand" width="20" height="20" src="{{ asset('/img/logo.png') }}"> {{ SITE_NAME }}</span>
    	</a>

    	<!-- Header Navbar -->
		<nav class="navbar navbar-static-top" role="navigation">



				<!-- Sidebar toggle button-->
			    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
			    	<span class="sr-only">Toggle navigation</span>
			    </a>

			    <!-- Navbar Right Menu -->
				<div class="navbar-custom-menu">

					<ul class="nav navbar-nav">


						<!-- /.messages-menu -->

	                    <!-- Notifications Menu
	                    <li class="dropdown notifications-menu">
	                        Menu toggle button
	                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	                            <i class="fa fa-bell-o"></i>
	                            <span class="label label-warning">10</span>
	                        </a>
	                        <ul class="dropdown-menu">
	                            <li class="header">You have 10 notifications</li>
	                            <li>
	                                Inner Menu: contains the notifications
	                                <ul class="menu">
	                                    <li>
											start notification
	                                        <a href="#">
	                                            <i class="fa fa-users text-aqua"></i> 5 new members joined today
	                                        </a>
	                                    </li>
										end notification
	                                </ul>
	                            </li>
	                            <li class="footer"><a href="#">View all</a></li>
	                        </ul>
	                    </li> -->

                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <!-- <img src="{{ asset("/bower_components/admin-lte/dist/img/user2-160x160.jpg") }}" class="user-image" alt="User Image"/> -->
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">{{Auth::user()->name}}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <!-- <img src="{{ asset("/bower_components/admin-lte/dist/img/user2-160x160.jpg") }}" class="img-circle" alt="User Image" /> -->
                                    <p>
                                        {{Auth::user()->email}} IBS
                                        <small>Member since {{Auth::user()->created_at}}</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Followers</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Sales</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Friends</a>
                                    </div>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="{{route('user.show', Auth::user()->id)}}" class="btn btn-default btn-flat">Profile</a>
										<a href="{{ route('user.edit', Auth::user()->id) }}" class="btn btn-default btn-flat">Update</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{{ route('logout') }}" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>

					</ul>

				</div>


		</nav>

	</header>

www/resources/views/layout/partials/sidebar.blade.php
    <!-- Left side column. contains the logo and sidebar -->
	<aside class="main-sidebar">

		<!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset("/bower_components/admin-lte/dist/img/user2-160x160.png") }}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>{{Auth::user()->name}}</p>
                <!-- Status -->
                <!-- <a href="#"><i class="fa fa-circle text-success"></i> Online</a> -->
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="{{ url('/search') }}" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="query" class="form-control" placeholder="Search..."/>
          		<span class="input-group-btn">
            		<button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
          		</span>
            </div>
        </form>
        <!-- /.search form -->
		<!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form" onsubmit="return false">
            <div class="input-group">
				<select class="form-control" name="select-section" id="select-section">
				</select>
          		<span class="input-group-btn">
            		<button onclick="showItemBySection();" name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
          		</span>
            </div>
        </form>
        <!-- /.search form -->

		<!-- Sidebar Menu -->
        <ul class="sidebar-menu">
        	<li class="header">Main Navigation</li>
            <!-- Optionally, you can add icons to the links -->
            <li class="active"><a href="{{ url('/') }}"><i class="fa fa-home"></i> <span>Home</span></a></li>
			<li><a href="{{ route('item.create') }}"><i class="fa fa-plus"></i> <span>Post an Item</span></a></li>
			<li><a href="{{ url('/myitem', Auth::user()->id) }}"><i class="fa fa-check-square"></i> <span>Inventory</span></a></li>
            <!-- <li><a href="{{ url('/') }}"><i class="fa fa-forumbee"></i> <span>Forums</span></a></li> -->
            <li><a href="{{ url('/about') }}"><i class="fa fa-info"></i> <span>About Us</span></a></li>
			<li><a href="{{ route('forums.index') }}"><i class="fa fa-info"></i> <span>Open Forums</span></a></li>
        </ul><!-- /.sidebar-menu -->

	</aside>